function xdot = SymDynamics3DoF(in1,in2,in3)
%SymDynamics3DoF
%    XDOT = SymDynamics3DoF(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Feb-2025 19:07:15

I = in3(3,:);
L = in3(2,:);
gimbal1 = in2(2,:);
mass = in3(1,:);
theta1 = in1(5,:);
thrust1 = in2(1,:);
v1 = in1(3,:);
v2 = in1(4,:);
w1 = in1(6,:);
t2 = gimbal1+theta1;
t3 = 1.0./mass;
xdot = [v1;v2;t3.*thrust1.*cos(t2);t3.*thrust1.*sin(t2)-9.81e+2./1.0e+2;w1;-(L.*thrust1.*sin(gimbal1))./I];
end
