function j_b = SymUJacobian3DoF(in1,in2,in3)
%SymUJacobian3DoF
%    J_B = SymUJacobian3DoF(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Feb-2025 19:07:17

I = in3(3,:);
L = in3(2,:);
gimbal1 = in2(2,:);
mass = in3(1,:);
theta1 = in1(5,:);
thrust1 = in2(1,:);
t2 = gimbal1+theta1;
t4 = 1.0./I;
t6 = 1.0./mass;
t3 = cos(t2);
t5 = sin(t2);
j_b = reshape([0.0,0.0,t3.*t6,t5.*t6,0.0,-L.*t4.*sin(gimbal1),0.0,0.0,-t5.*t6.*thrust1,t3.*t6.*thrust1,0.0,-L.*t4.*thrust1.*cos(gimbal1)],[6,2]);
end
