function j_a = SymXJacobian3DoF(in1,in2,in3)
%SymXJacobian3DoF
%    J_A = SymXJacobian3DoF(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    20-Feb-2025 19:07:17

gimbal1 = in2(2,:);
mass = in3(1,:);
theta1 = in1(5,:);
thrust1 = in2(1,:);
t2 = gimbal1+theta1;
t3 = 1.0./mass;
j_a = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-t3.*thrust1.*sin(t2),t3.*thrust1.*cos(t2),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0],[6,6]);
end
