function j_b = SymDynamics5DoF_j_b(in1,in2,in3)
%SymDynamics5DoF_j_b
%    J_B = SymDynamics5DoF_j_b(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    22-Feb-2025 13:55:42

I = in3(3,:);
L = in3(2,:);
mass = in3(1,:);
theta1 = in1(7,:);
theta2 = in1(8,:);
theta3 = in1(9,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = cos(theta3);
t5 = sin(theta1);
t6 = sin(theta2);
t7 = sin(theta3);
t8 = 1.0./I;
t9 = 1.0./mass;
t10 = L.*t8;
j_b = reshape([0.0,0.0,0.0,t3.*t9,t5.*t6.*t9,-t2.*t6.*t9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t6.*t7.*t9,t9.*(t2.*t4-t3.*t5.*t7),t9.*(t4.*t5+t2.*t3.*t7),0.0,0.0,0.0,0.0,-t10,0.0,0.0,0.0,t4.*t6.*t9,-t9.*(t2.*t7+t3.*t4.*t5),-t9.*(t5.*t7-t2.*t3.*t4),0.0,0.0,0.0,t10,0.0],[11,3]);
end
